#BN-26 chores: Setup Docker
atlp-rwanda/ecommerce-app-cogito-bn pull request #11
Opened 2023-03-30 11:41 UTC by Honore123

# PR Description
This PR creates a docker config for the backend whereby it contains both database(Postgres) container
and node js container.
# Description of tasks that were expected to be completed
List all the tasks and sub-tasks that were assigned to you Make sure you check every completed task. list them in this style
- [ ] An image of the backend application has been created
- [ ] Database is running in a docker container
- [ ] Both docker images can communicate while up and running
# Description of tasks that were expected to be completed and that are not yet completed
- [ ] Both docker images can communicate while up and running

# How this may be tested?
1. Install docker on your device; visit [https://www.freecodecamp.org/news/the-docker-handbook/#how-to-install-docker](url) to learn more
2. run `docker-compose up -d --build`
3. open your browser and visit `localhost:9090` for accessing the node server
4. You can also visit `localhost:8080` to access the Postgres database using admire
5. In adminer choose `PostgreSQL`
6. Server insert `postgres`
7. Fill all the textarea according to `.env`
8. then click login

# Screenshots (If appropriate/applicable)
<img width="678" alt="Screenshot 2023-03-30 at 1 36 44 PM" src="https://user-images.githubusercontent.com/39374321/228824065-0b5f69c3-cbcf-4270-a516-841deb8b7f20.png">
Node server

<img width="761" alt="Screenshot 2023-03-30 at 1 33 19 PM" src="https://user-images.githubusercontent.com/39374321/228823458-93be5019-87f3-4258-b247-dd0e0f35fdd9.png">
Adminer Login page

<img width="851" alt="Screenshot 2023-03-30 at 1 33 47 PM" src="https://user-images.githubusercontent.com/39374321/228823480-33f83960-dda4-4697-9d77-faf283aeb319.png">

Adminer dashboard page

# Please check this Checklist before you submit your PR:
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [ ] My code generates no warnings
- [ ] There are no vulnerabilities

2023-04-03 10:25 UTC, Lydie260 submitted a review, later dismissed

2023-04-03 10:30 UTC, kunda4 approved these changes, later dismissed

2023-04-03 11:58 UTC, sezeranoJchrisostome requested changes

2023-04-03 11:58 UTC, sezeranoJchrisostome commented on src/index.js
> +
Database initialization has been already initialized. I don't why we have this here

2023-04-03 11:58 UTC, sezeranoJchrisostome commented on src/index.js
> +import options from "./docs/apidoc";
let's use prettier eslint to format the codes

2023-04-03 12:05 UTC, chrisostome01 requested changes

2023-04-03 12:05 UTC, sezeranoJchrisostome commented on src/database/config/config.json
> +    "host": "postgres",
Also here I would suggest that we could have different database names for the different use cases.

2023-04-06 11:32 UTC, sezeranoJchrisostome approved these changes
# LGTM 🚀

2023-04-06 11:32 UTC, merged