BN#24-Setup Continuous Integration & Quality Assurance pipeline
atlp-rwanda/ecommerce-app-cogito-bn pull request #13
Opened 2023-03-30 15:20 UTC by Lydie260

# PR Description
Please include a brief description of the pull request you want to raise.
# Description of tasks that were expected to be completed
List all the tasks and sub-tasks that were assigned to you Make sure you check every completed task. list them in this style
- [ ]  Configured Testing environment with either Mocha, Chai and Sinon, or Jest and Supertest to ensure that all functionalities are tested before deployment.
- [ ] GitHub Actions is configured as a continuous integration service used to build and test the app.
- [ ] GitHub Actions  badge has been added to your repo
- [ ] Configured CodeClimate for code analysis and Maintainability checking.
# Description of tasks that were expected to be completed and that are not yet completed

# How this may be tested?
Please describe the tests that you ran to verify your functionalities. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration.
1. run `npm i` to install all required dependencies
2. run `npm  test`
# Screenshots (If appropriate/applicable)
Provide screenshots related to your PR in case it's appropriate and applicable
# Please check this Checklist before you submit your PR:
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [ ] My code generates no warnings
- [ ] There are no vulnerabilities

2023-03-30 15:50 UTC, Honore123 submitted a review, later dismissed

2023-03-30 16:26 UTC, kunda4 submitted a review, later dismissed

2023-03-30 16:33 UTC, sezeranoJchrisostome requested changes
# Well done @Niyobuzima @Lydie260 
One more thing we may have forgotten one acceptance criteria related to badges, please would also work on it?

2023-03-30 16:33 UTC, chrisostome01 commented on .github/workflows/gitActions.yml
> +    branches: [ "develop" ]
Would you please include the main branch here too?

2023-03-31 06:24 UTC, Niyobuzima reviewed
The issue has been resolved, as you can see the issue was having a conflict with the develop branch on package json because they were duplicates of the dependencies check if the issue is resolved and approve

2023-04-04 11:50 UTC, closed without merging