#BN-7 feature: Create Roles and Set Permissions
atlp-rwanda/ecommerce-app-cogito-bn pull request #23
Opened 2023-04-06 09:55 UTC by kunda4

# PR Description
Admin should be able to assign various users to various roles. There should also be a role for the admin account itself. This will allow only accounts with particular roles permission to peform particular actions.
# Description of tasks that were expected to be completed
List all the tasks and sub-tasks that were assigned to you Make sure you check every completed task. list them in this style
- [ ] Create multiple users on the system and an admin
- [ ] admin assigns a particular user to a particular role
- [ ] the user can only perform actions allowed by their role.
- [ ] Document feature using swagger
OPTIONAL FEATURE (CHECK WITH MANAGER)
- [ ] Each role should have a list of permissions attached to them.
- [ ] Admin should be able to add and remove permissions from particular roles.
# Description of tasks that were expected to be completed and that are not yet completed
- [ ] the user can only perform actions allowed by their role.
- [ ] Document feature using swagger
OPTIONAL FEATURE (CHECK WITH MANAGER)
- [ ] Each role should have a list of permissions attached to them.
- [ ] Admin should be able to add and remove permissions from particular roles.
# How this may be tested?
Please describe the tests that you ran to verify your functionalities. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration.
1. run `npm i` to install all required dependencies
2. run `npm run dev`
3. step 3
4. step 4...
# Screenshots (If appropriate/applicable)
Provide screenshots related to your PR in case it's appropriate and applicable
# Please check this Checklist before you submit your PR:
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [ ] My code generates no warnings
- [ ] There are no vulnerabilities

2023-04-23 03:57 UTC, sezeranoJchrisostome requested changes
# Well done @kunda4 the codes are really well structured however here are a couple of things that we need to work on.

- Improve consistency in your code structure: some lines of code are written differently but in a different way but the same context. `message` and `Message` or `error` instead of `message`
- You can generate you own seeds instead of reusing same files

2023-04-23 03:57 UTC, sezeranoJchrisostome commented on src/controllers/permController.js
> +                    { permName, description },
Better to have permName as permssionName

2023-04-23 03:57 UTC, sezeranoJchrisostome commented on src/controllers/permController.js
Please consider formatting this file eslint prettier

2023-04-23 03:57 UTC, sezeranoJchrisostome commented on src/controllers/permController.js
> +        .json({ message: req.t('permission_create_message'), data: newPermission });
remember to include you statusCode in the response too

2023-04-23 03:57 UTC, sezeranoJchrisostome commented on src/controllers/permController.js
> +            console.log('error ' + err);
Remove this console

2023-04-23 03:57 UTC, sezeranoJchrisostome commented on src/controllers/permController.js
> +    const { permName, description } = req.body;
PermName, should be meaningful.

2023-04-23 03:57 UTC, sezeranoJchrisostome commented on src/controllers/permController.js
> +            res.status(200).json({ statusCode: 200, data: permissions });
Message is missing in your response

2023-04-23 03:57 UTC, sezeranoJchrisostome commented on src/controllers/permController.js
> +                return res.status(200).json({ statusCode: 200, data: permissions });
Message is missing here

2023-04-23 03:57 UTC, sezeranoJchrisostome commented on src/controllers/permController.js
> +                    Message: req.t('id_unexist_message'),
Stay consistent `Message` is completely different from `message`

2023-04-23 03:57 UTC, sezeranoJchrisostome commented on src/controllers/roleController.js
> +            return res.status(201).json({ message: req.t('set-role-message'), response: userRoles })
snake case would be good instead `set-role-message` you can use `set_role_message`

2023-04-23 03:57 UTC, sezeranoJchrisostome commented on src/controllers/roleController.js
> +            console.error(error);
remove this console

2023-04-23 03:57 UTC, sezeranoJchrisostome commented on src/controllers/roleController.js
> +                .json({ statusCode: 400, error: "Server error" });
status code are deferent...

2023-04-23 03:57 UTC, sezeranoJchrisostome commented on src/controllers/userController.js
> +  if (!firstName || !lastName || !email || !password || !phone || !roleId) {
Use Joi to validate all of those inputs

2023-04-23 03:57 UTC, sezeranoJchrisostome commented on src/controllers/permController.js
> +            return res.status(500).json({ error: error.message })
Use message here instead of error to improve consistency

2023-04-23 04:04 UTC, sezeranoJchrisostome requested changes

2023-04-23 04:04 UTC, chrisostome01 commented on Makefile
> +>>>>>>> a84c243cf595935bb3c658307b81e93305ae41fb
I those conflicts are not supposed to be here..?

2023-04-23 04:04 UTC, sezeranoJchrisostome commented on package.json
> +    "make-model": "npx sequelize-cli model:generate --name users --attributes firstName:string,lastName:string,email:string, password:string, role:string",
Remove those demo data `users firstName:string,lastName:string,email:string, password:string, role:string`

2023-04-23 04:04 UTC, sezeranoJchrisostome commented on package.json
> +    "make-seed": "npx sequelize-cli seed:generate --name demo-users",
remove also this `--name demo-users` this should be someone else's inputs

2023-04-23 04:04 UTC, sezeranoJchrisostome commented on src/controllers/permController.js
permssionController would be good choice and it wold more descriptive enough

2023-04-23 10:06 UTC, Honore123 approved these changes
🚀

2023-04-24 06:57 UTC, sezeranoJchrisostome approved these changes
# LGTM

2023-04-24 06:57 UTC, merged