#36 feature: Update Profile
atlp-rwanda/ecommerce-app-cogito-bn pull request #26
Opened 2023-04-09 20:31 UTC by Honore123

- Profile accessible publicly
- Update profile [Finishes #36]

# PR Description
This PR allow users to update their profile and make them accessible publicly
# Description of tasks that were expected to be completed
List all the tasks and sub-tasks that were assigned to you Make sure you check every completed task. list them in this style
- [ ] The vendor or buyer should be able to update information about their own profile.
- [ ] The vendor or buyer's profile should be accessible publicly.
- [ ] Appropriate error messages are displayed on unsuccessful attempts.
# Description of tasks that were expected to be completed and that are not yet completed
- [ ] Appropriate error messages are displayed on unsuccessful attempts.
# How this may be tested?
Please describe the tests that you ran to verify your functionalities. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration.
1. run `make build` to install all required dependencies
2. visit the `/api-docs` endpoint to access Swagger UI
3. Test profile endpoint `GET` and `PUT`
# Screenshots (If appropriate/applicable)
Provide screenshots related to your PR in case it's appropriate and applicable
# Please check this Checklist before you submit your PR:
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [ ] My code generates no warnings
- [ ] There are no vulnerabilities

2023-04-14 16:00 UTC, EvelyneUmubyeyi requested changes
Hello Honore, your endpoints for getting and updating profile work properly. I noticed some few things that you can work on to improve your code:
- Add your endpoints documentation to a separate file in the docs folder
- Moving 'isUserExist' function from the profileController file to another file in the middleware folder
- I think it would be best to return data as an object in the response instead of a list as you did i.e. data: [object]
- There are also no response sent when the user sends an empty request body or non-existant columns on updating profile endpoint

2023-04-15 09:21 UTC, sezeranoJchrisostome requested changes

2023-04-15 09:21 UTC, sezeranoJchrisostome commented on src/index.js
>  app.get('/', (req, res) => res.status(200).json({ status: 200, message: req.t('welcome_message') }));
Please checkout the reason why the translation is not working here

2023-04-15 09:21 UTC, sezeranoJchrisostome commented on src/database/seeders/20230326221727-demo-cogito.js
The seeds are not really working, 
[Preview](https://cogito-api-pr-26.onrender.com/api-docs/#/Profile/put_profile__id_)

2023-04-15 09:21 UTC, sezeranoJchrisostome commented on src/database/migrations/20230326212313-create-user.js
It would be better if this file is not tracked down by codeclimate

2023-04-15 09:21 UTC, sezeranoJchrisostome commented on src/database/seeders/20230326221727-demo-cogito.js
Let also ignore this file in the codeclimate please

2023-04-15 09:31 UTC, sezeranoJchrisostome requested changes

2023-04-15 09:31 UTC, sezeranoJchrisostome commented on src/controllers/profileController.js
> +    console.error(error);
remove this console

2023-04-15 09:31 UTC, sezeranoJchrisostome commented on src/controllers/profileController.js
> +};
Please, implement error handling here too

2023-04-15 09:31 UTC, sezeranoJchrisostome commented on src/controllers/profileController.js
> +  next();
Please, implement error handling here too and move it inside middleware also

2023-04-19 17:46 UTC, Lydie260 approved these changes, later dismissed

2023-04-20 05:39 UTC, sezeranoJchrisostome approved these changes
# LGTM

2023-04-20 08:46 UTC, EvelyneUmubyeyi approved these changes
Code meets the desired requirements.

2023-04-20 09:07 UTC, merged