#30 feature: logout from the App
atlp-rwanda/ecommerce-app-cogito-bn pull request #32
Opened 2023-04-18 11:40 UTC by nellykawera

# PR Description
Please include a brief description of the pull request you want to raise.
The admin, vendor and buyer should be able to logout
# Description of tasks that were expected to be completed
List all the tasks and sub-tasks that were assigned to you Make sure you check every completed task. list them in this style
- [x] As an authenticated user, I want to be able to logout, so that none else can access my account as well
# Description of tasks that were expected to be completed and that are not yet completed
- [x ] Authenticated user should be able to logout.
- [x ] Only authenticated user should be able to access protected resourses/URLs
- [x ] Appropriate error messages are displayed on unsuccessful attempts
# How this may be tested?
Please describe the tests that you ran to verify your functionalities. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration.
1. run `npm i` to install all required dependencies
2. run `npm run dev`
3. swagGer UI "DELETE"
# Screenshots (If appropriate/applicable)
Provide screenshots related to your PR in case it's appropriate and applicable
# Please check this Checklist before you submit your PR:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented on my code, particularly in hard-to-understand areas
- [x] My code generates no warnings
- [x] There are no vulnerabilities

2023-04-18 17:38 UTC, uwdjany reviewed
well done!

2023-04-18 18:19 UTC, uwdjany submitted a review, later dismissed

2023-04-19 06:04 UTC, sezeranoJchrisostome requested changes

2023-04-19 06:04 UTC, chrisostome01 commented on src/locales/fr/translation.json
> +>>>>>>> 67efa140f34198bc0baf99d91940080127fad01a
Is this supposed to be here

2023-04-19 06:04 UTC, chrisostome01 commented on tests.js/testUser.test.js
> +/* eslint-disable indent */
Fix the linting issues instead of ignoring them

2023-04-19 06:04 UTC, chrisostome01 commented on tests.js/testUser.test.js
Consider formatting this file with prettier eslint

2023-04-19 06:04 UTC, sezeranoJchrisostome commented on src/controllers/UserController.js
> +
The logout functionality is not really working.
Uncomment these comments and make sure to handle errors

2023-04-19 06:04 UTC, sezeranoJchrisostome commented on src/controllers/UserController.js
> +  }
Use Joi for this validation

2023-04-19 06:04 UTC, sezeranoJchrisostome commented on src/controllers/UserController.js
> +  }
I would recommend wrapping this inside try and catch block

2023-04-26 05:30 UTC, sezeranoJchrisostome requested changes

2023-04-26 05:30 UTC, sezeranoJchrisostome commented on tests.js/testUser.test.js
Why is this file is deleted

2023-04-26 05:30 UTC, sezeranoJchrisostome commented on src/controllers/UserController.js
let us use one file for the user controller and I would take an example from how other controllers are being named and stick to the same casing..

2023-04-26 05:30 UTC, sezeranoJchrisostome commented on src/controllers/userController.js
> +  });
I think this is not enough to logout the user, would you try to improve this process?

2023-04-27 06:30 UTC, dushimeemma reviewed
Write the unit test for your endpoint please, otherwise good job!

2023-04-28 08:47 UTC, dushimeemma requested changes

2023-04-28 08:47 UTC, dushimeemma commented on src/tests/testUsers.test.js
> +});
Add logout functionality unit test

2023-05-01 08:45 UTC, nellykawera commented on src/tests/testUsers.test.js
> +});
I did thanks

2023-05-03 07:03 UTC, sezeranoJchrisostome requested changes, later dismissed

2023-05-03 07:03 UTC, sezeranoJchrisostome commented on src/controllers/userController.js
> +      res.status(200).json({ message: 'Logged out successfully' });
I think this message would be better if it is translated....

2023-05-03 14:02 UTC, dushimeemma requested changes

2023-05-03 14:02 UTC, dushimeemma commented on src/database/migrations/20220409220608-create-user.js
> +=======
what is the meaning of this line?

2023-05-03 14:02 UTC, dushimeemma commented on src/database/migrations/20220409220608-create-user.js
> +>>>>>>> 61173629cdf84ae40840eb4a389e2058bf3dedb9:src/database/migrations/20220409220608-create-user.js
what is the meaning of this line?

2023-05-03 14:02 UTC, dushimeemma commented on src/database/config/config.json
the config file should be a js file

2023-05-04 05:56 UTC, dushimeemma commented on src/database/config/config.json
Database config is a JS file @nellykawera please do rebase correctly.
`git pull --rebase origin develop`

2023-05-05 11:15 UTC, dushimeemma commented
> A deploy for your [Render](https://render.com) PR Server at https://cogito-api-pr-32.onrender.com just failed.
> 
> View details on your dashboard at https://dashboard.render.com/web/srv-cgv835hmbg54u99g37h0.

@nellykawera kindly check the reason why render is failing to deploy your branch

2023-05-08 07:25 UTC, Honore123 commented on src/tests/testUsers.test.js
> +      });
Add expected result

2023-05-08 08:00 UTC, Honore123 approved these changes
🚀

2023-05-08 08:23 UTC, dushimeemma approved these changes
Good job 👍

2023-05-08 08:23 UTC, uwdjany approved these changes

2023-05-08 08:27 UTC, merged