#BN-18: add and view products to the wishlist
atlp-rwanda/ecommerce-app-cogito-bn pull request #36
Opened 2023-04-26 16:42 UTC by Honore123

# Ticket Trello Link
[Link to Trello ticket](https://trello.com/c/oXlY8e1I/36-update-profile)
# PR Description
Allows buyers to add products to the wishlist and view the list
# Description of tasks that were expected to be completed
List all the tasks and sub-tasks that were assigned to you Make sure you check every completed task. list them in this style
- [ ] Validate that the buyer is logged in.
- [ ] Add the item to the buyer's wishlist.
- [ ] Retrieve the product details from the database.
- [ ] Store the updated wishlist in the buyer's account.
# Description of tasks that were expected to be completed and that are not yet completed
- [ ] None
# How this may be tested?
Please describe the tests that you ran to verify your functionalities. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration.
1. run `make build` to install all required dependencies
2. visit the `/api-docs` endpoint to access Swagger UI
3. Test wishlist endpoint `GET` and `POST`
# Screenshots (If appropriate/applicable)
Provide screenshots related to your PR in case it's appropriate and applicable
# Please check this Checklist before you submit your PR:
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [ ] My code generates no warnings
- [ ] There are no vulnerabilities

2023-04-26 17:12 UTC, uwdjany submitted a review, later dismissed
well done

2023-04-27 06:00 UTC, dushimeemma commented on src/config/config.json
can we hide our sensitive data using env variables?

2023-04-27 06:01 UTC, dushimeemma requested changes

2023-04-27 06:01 UTC, dushimeemma commented on src/config/config.json
can we use env variables to hide our sensitive data?

2023-04-27 09:44 UTC, Illustre13 reviewed
Well Done Honore!

2023-05-04 13:05 UTC, uwdjany approved these changes

2023-05-04 15:07 UTC, kunda4 approved these changes
Well done

2023-05-04 15:08 UTC, Charlesntwari approved these changes

2023-05-04 15:12 UTC, dushimeemma approved these changes
Good job 🥇 🥇 🥇

2023-05-04 15:14 UTC, merged