setting environment variables and added dotenv to the project
atlp-rwanda/ecommerce-app-cogito-bn pull request #5
Opened 2023-03-29 11:35 UTC by uwdjany

# PR Description
in this pull request ,I added dotenv to the project and set environment variables.
and I tried to configure the database, which I had converted from json to Js in order to configure a variable from the .env file.

# Description of tasks that were expected to be completed
List all the tasks and sub-tasks that were assigned to you Make sure you check every completed task. list them in this style
- [ ] Added dotenv to the project
- [ ] setting environment variables
- [ ] shared variable and managed using dotenv
- [ ] Moving to production switches to the correct environment
# Description of tasks that were expected to be completed and that are not yet completed
- [ ] None

# How this may be tested?
Please describe the tests that you ran to verify your functionalities. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration.
1. run `npm i` to install all required dependencies
2. run `npm start`
3. step 3
4. step 4...
# Screenshots (If appropriate/applicable)
Provide screenshots related to your PR in case it's appropriate and applicable
# Please check this Checklist before you submit your PR:
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [ ] My code generates no warnings
- [ ] There are no vulnerabilities

2023-03-29 14:25 UTC, sezeranoJchrisostome requested changes
# Great job @uwdjany 
Please consider naming the pull request title as the structure we defined for the team also I left some comments and they are mostly related to best practices please check them out too. 
Please try and integrate this [cross-env](https://www.npmjs.com/package/cross-env) to update the env according to the script running.

2023-03-29 14:25 UTC, sezeranoJchrisostome commented on src/database/config/config.js
Would please consider formatting this file with prettier?

2023-03-29 14:25 UTC, sezeranoJchrisostome commented on src/database/config/config.js
> +module.exports=config;
Would you try to ES6 here?
```suggestion
export default config;
```

2023-03-29 14:25 UTC, sezeranoJchrisostome commented on src/database/config/config.js
> +
These empty lines are not necessary. One line would be okay

2023-03-29 14:36 UTC, uwdjany commented on src/database/config/config.js
check again i have correct title and prettier does not work in my vs code.

2023-03-30 16:35 UTC, sezeranoJchrisostome approved these changes
LGTM 🚀

2023-03-30 16:36 UTC, kunda4 approved these changes

2023-03-30 16:38 UTC, merged