Buyer should be able to clear their cart
atlp-rwanda/ecommerce-app-cogito-bn pull request #59
Opened 2023-05-12 21:08 UTC by uwdjany

# PR Description
https://trello.com/c/KWfchsBs/23-buyer-should-be-able-to-clear-their-cart
List all the tasks and sub-tasks that were assigned to you Make sure you check every completed task. list them in this style
- [ ] The buyer's cart should be emptied
- [ ] The cart total should be reset to zero
- [ ] A cart cleared confirmation message should be sent to the frontend to be displayed to the buyer
# Description of tasks that were expected to be completed and that are not yet completed
- [ ] None
# How this may be tested?
Please describe the tests that you ran to verify your functionalities. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration.
1. run `npm i` to install all required dependencies
2. run `npm run dev`
3. step 3
4. step 4...
# Screenshots (If appropriate/applicable)
Provide screenshots related to your PR in case it's appropriate and applicable
# Please check this Checklist before you submit your PR:
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [ ] My code generates no warnings
- [ ] There are no vulnerabilities

2023-05-15 07:47 UTC, kunda4 reviewed
Well done djanati just for making code look great remove that commented line

2023-05-15 07:47 UTC, kunda4 commented on src/controllers/product/clearCartController.js
> +    // }
Remove this commented Line

2023-05-15 07:47 UTC, kunda4 commented on src/database/models/cart.js
> +      //date_added: DataTypes.STRING,
Remove this too

2023-05-15 08:02 UTC, uwdjany commented on src/database/models/cart.js
> +      //date_added: DataTypes.STRING,
Done!

2023-05-18 08:09 UTC, kunda4 submitted a review, later dismissed

2023-05-19 05:13 UTC, dushimeemma approved these changes, later dismissed
Your commit message should match standard.
example on [wiki](https://github.com/atlp-rwanda/engineering-playbook/wiki)

2023-05-19 05:16 UTC, dushimeemma requested changes
Your commit message should match standard.
example on [wiki](https://github.com/atlp-rwanda/engineering-playbook/wiki)

2023-05-19 06:48 UTC, Niyobuzima approved these changes

2023-05-19 07:18 UTC, dushimeemma approved these changes

2023-05-19 07:18 UTC, merged