#BN-1 feat: Create discount coupons for sellers
atlp-rwanda/ecommerce-app-cogito-bn pull request #61
Opened 2023-05-16 14:44 UTC by EvelyneUmubyeyi

# Trello Card Link
https://trello.com/c/2LgDWBis

# PR Description
In this PR I created endpoints for seller to create a discount coupon on certain products, view all the coupons they have created, edit a coupon they have created, and an endpoint for a buyer to apply a coupon on their shopping items and get a discount during checkout.
  
# Description of tasks that were expected to be completed
List all the tasks and sub-tasks that were assigned to you Make sure you check every completed task. list them in this style
- [x] The system should allow sellers to create and manage coupon codes, which should be associated with their account ID
- [x] The system should allow sellers to view all coupon codes associated with their account ID and manage their usage and expiration dates. 
- [x] The system should allow buyers to apply valid coupon codes during checkout, and the discount should be applied to eligible products in the buyer's cart
- [x] The system should ensure that coupon codes are valid for the products in the buyer's cart and calculate the discount amount to be applied to each eligible product.
# Description of tasks that were expected to be completed and that are not yet completed
- [x] None
# How this may be tested?
Please describe the tests that you ran to verify your functionalities. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration.
1. run `npm i` to install all required dependencies
2. run `npm run dev`
3. Go to `localhost:<port number>/api-docs` to access swagger documentation
4. Test the endpoints and the coupon tag
# Screenshots (If appropriate/applicable)
Provide screenshots related to your PR in case it's appropriate and applicable
# Please check this Checklist before you submit your PR:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented on my code, particularly in hard-to-understand areas
- [x] My code generates no warnings
- [x] There are no vulnerabilities

2023-05-17 13:50 UTC, Illustre13 approved these changes, later dismissed

2023-05-17 14:05 UTC, Niyobuzima requested changes

2023-05-17 14:05 UTC, Niyobuzima commented on src/database/seeders/20230326221727-demo-cogito.js
> +        // {
why is lines commented

2023-05-17 14:32 UTC, Charlesntwari submitted a review, later dismissed

2023-05-17 14:34 UTC, Niyobuzima submitted a review, later dismissed

2023-05-17 19:30 UTC, Niyobuzima submitted a review, later dismissed

2023-05-18 06:17 UTC, dushimeemma requested changes
@EvelyneUmubyeyi please uncomment all the test cases that you have commented out.

2023-05-18 08:49 UTC, Charlesntwari submitted a review, later dismissed

2023-05-18 12:46 UTC, Niyobuzima approved these changes

2023-05-18 13:05 UTC, dushimeemma approved these changes
Good job 👍

2023-05-18 13:07 UTC, merged