feat(order status): read and update order status functionality
atlp-rwanda/ecommerce-app-cogito-bn pull request #70
Opened 2023-05-22 14:03 UTC by EvelyneUmubyeyi

# Trello card link 
https://trello.com/c/z052NHNg

# PR Description
In this PR I created an endpoint to allow buyers to check their order status and an endpoint to allow system administrators to update order status

# Description of tasks that were expected to be completed
List all the tasks and sub-tasks that were assigned to you Make sure you check every completed task. list them in this style
- [x] Create an endpoint to allow a buyer to check their order status
- [x] Create an endpoint to allow a system administrator to update an order status in real-time using web sockets

# Description of tasks that were expected to be completed and that are not yet completed
- [x] None

# How this may be tested?
Please describe the tests that you ran to verify your functionalities. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration.
1. run `npm i` to install all required dependencies
2. run `npm run dev`
3. Go to localhost:<port number>/api-docs to access swagger documentation
4. Test the endpoints under the orders tag

# Screenshots (If appropriate/applicable)
Provide screenshots related to your PR in case it's appropriate and applicable
# Please check this Checklist before you submit your PR:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented on my code, particularly in hard-to-understand areas
- [x] My code generates no warnings
- [x] There are no vulnerabilities

2023-05-23 13:18 UTC, Charlesntwari submitted a review, later dismissed

2023-05-23 14:43 UTC, Illustre13 submitted a review, later dismissed

2023-05-23 15:19 UTC, Niyobuzima approved these changes

2023-05-23 15:20 UTC, Niyobuzima requested changes
Resolve the conflict

2023-05-23 15:25 UTC, Niyobuzima submitted a review, later dismissed

2023-05-24 06:05 UTC, dushimeemma requested changes

2023-05-24 06:05 UTC, dushimeemma commented on src/controllers/order/orderController.js
> +  const { id } = req.body;
Why don't get the id from params rather than the body?

2023-05-24 06:05 UTC, dushimeemma commented on src/controllers/order/orderController.js
> +  console.log('id inside a controller', id);
Do we need this log in production?

2023-05-24 06:05 UTC, dushimeemma commented on src/controllers/order/orderController.js
> +  const { id, status, deliveryDate } = req.body;
get order id from params rather than body, I think it will be nice and clean.

2023-05-24 06:05 UTC, dushimeemma commented on src/controllers/order/orderController.js
> +  console.log('id inside a controller', id);
Safely remove this log statement.

2023-05-24 08:33 UTC, dushimeemma approved these changes

2023-05-24 08:36 UTC, merged