#BN-FIX: Confirmation
atlp-rwanda/ecommerce-app-cogito-bn pull request #82
Opened 2023-06-26 20:25 UTC by Niyobuzima

# PR Description
Please include a brief description of the pull request you want to raise.
# Description of tasks that were expected to be completed
List all the tasks and sub-tasks that were assigned to you Make sure you check every completed task. list them in this style
- [x] updated the comfirmation page to meant our projects requirements 

# Description of tasks that were expected to be completed and that are not yet completed
- [x] None

# How this may be tested?
Please describe the tests that you ran to verify your functionalities. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration.
1. run `npm i` to install all required dependencies
2. run `npm run dev`
# Screenshots (If appropriate/applicable)
Provide screenshots related to your PR in case it's appropriate and applicable
# Please check this Checklist before you submit your PR:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented on my code, particularly in hard-to-understand areas
- [x] My code generates no warnings
- [x] There are no vulnerabilities

2023-06-26 21:19 UTC, EvelyneUmubyeyi submitted a review, later dismissed

2023-06-27 00:34 UTC, dushimeemma requested changes

2023-06-27 00:34 UTC, dushimeemma commented on src/controllers/Auth/signupController.js
> +      html: `<p>${'clickLink'} <a href="https://cogito-api.onrender.com/user/confirm/${confirmationCode}">${'here'}</a> ${'toConfirmAccount'}.</p>`,
Please use environment variables rather than hard-coded values.

2023-06-27 11:40 UTC, dushimeemma approved these changes

2023-06-27 11:41 UTC, merged