#BN-FIX:update product
atlp-rwanda/ecommerce-app-cogito-bn pull request #84
Opened 2023-07-07 09:36 UTC by nellykawera

# PR Description
Fixed some issues with update product
# Description of tasks that were expected to be completed
List all the tasks and sub-tasks that were assigned to you Make sure you check every completed task. list them in this style
- [X] added feature fore product
# Description of tasks that were expected to be completed and that are not yet completed
- [X] none
# How this may be tested?
Please describe the tests that you ran to verify your functionalities. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration.
1. run `npm i` to install all required dependencies
2. run `npm run dev`
3. step 3
4. step 4...
# Screenshots (If appropriate/applicable)
Provide screenshots related to your PR in case it's appropriate and applicable
# Please check this Checklist before you submit your PR:
- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my code
- [X] I have commented on my code, particularly in hard-to-understand areas
- [X] My code generates no warnings
- [X] There are no vulnerabilities

2023-07-11 07:05 UTC, dushimeemma requested changes
Write another test case so that you can increase coverage a bit.

2023-07-12 15:44 UTC, Charlesntwari reviewed
everything is good though i request you to reduce number of commits

2023-07-12 19:36 UTC, Niyobuzima approved these changes
LGTM!!!!!

2023-07-13 05:56 UTC, dushimeemma approved these changes

2023-07-13 05:56 UTC, merged